# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Platform"
  url = "platform/"
  weight = 10

[[main]]
  name = "Membership"
  url = "membership/"
  weight = 15

[[main]]
  name = "About"
  identifier = "about"
  weight = 25

  [[main]]
  parent = "about"
  name = "Our mission"
  url = "mission/"
  weight = 10

  [[main]]
  parent = "about"
  name = "Open Practices"
  url = "open-practices/"
  weight = 12

  [[main]]
  parent = "about"
  name = "Right to Replicate"
  url = "right-to-replicate/"
  weight = 13

  [[main]]
  parent = "about"
  name = "Commitment to Open Technology"
  url = "open-technology/"
  weight = 13

  [[main]]
  parent = "about"
  name = "Our organization and team"
  url = "organization/"
  weight = 15

  [[main]]
  parent = "about"
  name = "How we're funded"
  url = "about/funding/"
  weight = 16

  [[main]]
  parent = "about"
  name = "Origin story"
  url = "founders/"
  weight = 50

  [[main]]
  parent = "about"
  name = "Design and brand assets"
  url = "brand/"
  weight = 70

  [[main]]
  parent = "about"
  name = "Jobs at 2i2c"
  url = "jobs/"
  weight = 60

[[main]]
  name = "Impact"
  weight = 30

[[main]]
  name = "Impact stories"
  parent = "Impact"
  url = "impact/"
  weight = 11

[[main]]
  name = "Case studies"
  parent = "Impact"
  url = "case-studies/"
  weight = 14

[[main]]
  name = "Member communities"
  parent = "Impact"
  url = "members/"
  weight = 12
  
[[main]]
  name = "Collaborators and funders"
  parent = "Impact"
  url = "collaborators/"
  weight = 13

[[main]]
  name = "Roadmap <span class=\"menu-badge\">NEW</span>"
  # This is actually served from the 2i2c-org/roadmap repository
  url = "https://2i2c.org/roadmap/"
  weight = 40

[[main]]
  name = "Docs"
  url = "https://docs.2i2c.org"
  weight = 50

[[main]]
  name = "Blog"
  url = "/blog"
  weight = 60

[[main_right]]
  name = "Join our network"
  url = "/join"
  weight = 90
