[build]
  command = "python scripts/add_slugs_to_blog_posts.py && pip install -r requirements.txt && python scripts/extract_org_logos.py && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.3"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "python scripts/add_slugs_to_blog_posts.py && pip install -r requirements.txt && python scripts/extract_org_logos.py && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "python scripts/add_slugs_to_blog_posts.py && pip install -r requirements.txt && python scripts/extract_org_logos.py && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
